baseURL = 'https://pedrobyjoao.github.io'
languageCode = 'en-us'
title = 'JP, an ape'
theme = 'typo'

[taxonomies]
  tag = 'tags'

[params]
  # Meta description
  description = "A Reality Blog"

  # Appearance settings
  theme = 'auto'
  colorPalette = 'default'
  hideHeader = false

  # Intro on main page, content is markdown
  homeIntroTitle = "Hi, conscious being"
  homeIntroContent = """
  An ape trying to make sense.  
  Feels peace, joy and love  
  but also sorrow, anger and solitude.  

  Tries to understand,  
  gets lost.  
  Feel sad about  
  when once felt peace.  

  Searching.  
  I'm searching.  
  Although, maybe there is nothing to be found.  
  And everything that I need is already here.  

  Anyway dear me, be lightly.  
  Take everything lightly.  
  Even when it seems heavy.  

  -----------------------------

  Currently reading: 
- Mind illuminated
- They both die at the end, Adam Silvera
  """

  # Collection to display on home
  homeCollectionTitle = 'Posts'
  homeCollection = 'posts'

  # Lists parameters
  paginationSize = 100
  listSummaries = false
  listDateFormat = '2 Jan 2006'

  # Breadcrumbs
  breadcrumbs = true

# Social icons
# [[params.social]]
#   name = "linkedin"
#   url = "https://pedrobyjoao.github.io/about"

[[params.social]]
  name = "github"
  url = "https://github.com/PedrobyJoao"

# Menu pages
[[params.menu]]
    name = "home"
    url = "/"

[[params.menu]]
    name = "Posts"
    url = "/posts"

[[params.menu]]
    name = "Books"
    url = "/books"

# Syntax highlight on code blocks
[markup.highlight]
  style = 'algol'

# Giscus comments
[params.giscus]
  enable = false
  repo = "user/repo"
  repoId = "repoId"
  category = "General"
  categoryId = "categoryId"
  mapping = "pathname"
  theme = "preferred_color_scheme"
