baseURL = 'https://apemortalis.com'
languageCode = 'en-us'
title = 'JP, an ape'
theme = 'typo'

[taxonomies]
  tag = 'tags'

[params]
  # Meta description
  description = "A Reality Blog"

  # Appearance settings
  theme = 'auto'
  colorPalette = 'default'
  hideHeader = false

  # Intro on main page, content is markdown
  homeIntroTitle = "Hi, conscious being"
  homeIntroContent = """
  Holy, I am the universe.  
  We are the universe.  
  We are all one.  

  There is no "I".  
  There is no self in variety.  
  We are all just different computing processes  
  occurring in the same machinery.  

  That is no mysticism,  
  no fiction  
  or religion.  

  We are **physically** one.  
  One.  
  1.  

  -----------------------------

  Currently reading: 
- The Glass Bead Game
- Mind illuminated
  """

  # Collection to display on home
  homeCollectionTitle = 'Posts'
  homeCollection = 'posts'

  # Lists parameters
  paginationSize = 100
  listSummaries = false
  listDateFormat = '2 Jan 2006'

  # Breadcrumbs
  breadcrumbs = true

# Social icons
# [[params.social]]
#   name = "linkedin"
#   url = "https://pedrobyjoao.github.io/about"

[[params.social]]
  name = "github"
  url = "https://github.com/PedrobyJoao"

# Menu pages
[[params.menu]]
    name = "home"
    url = "/"

[[params.menu]]
    name = "Posts"
    url = "/posts"

[[params.menu]]
    name = "Books"
    url = "/books"

# Syntax highlight on code blocks
[markup.highlight]
  style = 'algol'

# Giscus comments
[params.giscus]
  enable = false
  repo = "user/repo"
  repoId = "repoId"
  category = "General"
  categoryId = "categoryId"
  mapping = "pathname"
  theme = "preferred_color_scheme"
